name: API Infrastructure

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to"
      aws_region:
        required: false
        type: string
        description: "The AWS region to deploy to"
        default: "eu-west-1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      AWS_REGION: ${{ inputs.aws_region }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Serverless Framework
        run: npm i serverless -g

      - name: Install dependencies
        working-directory: services/helpdesk-service
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Validate Serverless config (print)
        working-directory: services/helpdesk-service
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls print --stage ${{ env.ENVIRONMENT }} --config serverless.ireland.yml --path functions

      - name: Package without deploy (noDeploy)
        working-directory: services/helpdesk-service
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls package --stage ${{ env.ENVIRONMENT }} --config serverless.ireland.yml

      - name: Deploy to AWS
        working-directory: services/helpdesk-service
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: sls deploy --stage ${{ env.ENVIRONMENT }} --region eu-west-1 --config serverless.ireland.yml

      # - name: Run DB Migrations
      #   run: |
      #     aws lambda invoke \
      #       --function-name heldesk-service-${{ inputs.environment }}-runMigration \
      #       --invocation-type RequestResponse \
      #       --cli-binary-format raw-in-base64-out \
      #       invocation-result.json
      #     cat invocation-result.json

      # - name: Run DB Seeding
      #   run: |
      #     aws lambda invoke \
      #       --function-name helpdesk-service-${{ inputs.environment }}-runSeeder \
      #       --invocation-type RequestResponse \
      #       --cli-binary-format raw-in-base64-out \
      #       invocation-result.json
      #     cat invocation-result.json
